/*
 *Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
 */

package project.euler.pkg2;

/**
 *
 * @author Daniel
 */
public class ProjectEuler2 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        int sum = 0;
        int num1 = 0;   //1st term of fibonacci
        int num2 = 1;   //2nd term of fibonacci
        int z;
        
        do {
            z = num1 + num2;
            num1 = num2;
            num2 = z;
            if (num2 % 2 ==0) {
                sum += num2;
            } 
        } while (num2 < 4000000);
    System.out.println(sum);
    }
}
